on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: lee3jjang/myaction@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - name: 에니악입니다
        run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash